/**
 * DesignerOutput: Produced by the Designer agent.
 * The frontend renders the palette swatches, mockup image, logo,
 * brand voice guidelines, and secondary palette on the Design tab.
 */
export interface DesignerOutput {
  /** URL to the generated landing page mockup image. */
  mockupUrl: string;
  /** Full HTML code of the generated mockup. Used by the Developer agent. */
  exportedCode: string;
  /** URL to the primary logo image generated by Imagen. */
  logoUrl: string;
  /** Array of alternative logo variant URLs. */
  logoVariants: string[];
  /** Primary 3-color brand palette. */
  palette: {
    /** Main brand color in hex. Used for primary buttons and headings. */
    primary: string;
    /** Supporting color in hex. Used for backgrounds and cards. */
    secondary: string;
    /** Pop color in hex. Used for highlights and hover states. */
    accent: string;
  };

  /** Brand voice guidelines. Rendered as a style guide card. */
  brand_voice: {
    /** 2-3 word tone label, e.g. "warm and direct". */
    tone: string;
    /** 3 examples of language the brand should use. Each under 10 words. */
    do_say: string[];
    /** 3 examples of language the brand should avoid. Each under 10 words. */
    avoid: string[];
  };
  /** One paragraph on how to apply the brand consistently across touchpoints. */
  usage_guidelines: string;
  /** 3-5 supporting colors for backgrounds, dividers, and secondary UI. */
  secondary_palette: Array<{
    /** Color name, e.g. "Soft Slate". */
    name: string;
    /** Hex code. */
    hex: string;
    /** Where and how to use this color. Example: "Use for card backgrounds and section dividers." */
    usage: string;
  }>;
}
